### ISSUE TITLE
Include GitHub topics

### ISSUE THREAD

**Issue by thiagodp** [sindresorhus/pupa#11]
I could not remember the project name and had to find it manually to recommend it to a friend.

**Comment by sindresorhus** [comment]
I added some topics. Let me know if you have any more suggestions for topics ;)

**Comment by sindresorhus** [comment]
Also, probably easier to find stuff if you search for npm packages specifically: https://npms.io/search?q=micro+templating

**Comment by thiagodp** [comment]
Thank you. Some (additional) suggestions: `string` and `parameter`.

**Comment by thiagodp** [comment]
It would be nice if GitHub could recognize `keywords` in `package.json`. Duplicate work...

**Comment by sindresorhus** [comment]
I agree. You should send a feature request: support@github.com ;)

**Comment by thiagodp** [comment]
Sent, Ticket ID 300843 :)
