### ISSUE TITLE
Template matches incorrect values making them undefined.

### ISSUE THREAD

**Issue by RIP21** [sindresorhus/pupa#13]
I have a `package.json` file in which I want to replace only `name` field of it.
It's all good, but I also have entries like
```
  "lint-staged": {
    "*.{json,md,css,graphql,html}": [
      "prettier --write"
    ],
    "*.{ts,js,jsx,tsx}": [
      "eslint --fix --ext js,jsx,tsx,ts --max-warnings 0"
    ]
  },
```
So these glob patterns transform info `undefined`

```
  "lint-staged": {
    "*.undefined": [
      "prettier --write"
    ],
    "*.undefined": [
      "eslint --fix --ext js,jsx,tsx,ts --max-warnings 0"
    ]
  },
```
I'm unsure of it's expected behavior as inside there are no dots as a separators but commas.

**Comment by RIP21** [comment]
@sindresorhus I see that you have fixed that already :D I just finally get back to this task again and wanted to contribute.
Can you publish a new version maybe and close this one for good? :)

**Comment by sindresorhus** [comment]
I left the issue open as we still need to not replace when the value is `undefined`.  My regex tweaks only fixed this exact case, but there might be other cases.

I did indeed forget to publish the regex tweak though, which is done now.

**Comment by sindresorhus** [comment]
Continued in https://github.com/sindresorhus/pupa/issues/19
