### ISSUE TITLE
Does not support non-english letters?

### ISSUE THREAD

**Issue by einarpersson** [sindresorhus/pupa#27]
Hi! Thanks for providing a useful lib! 👍 

I discovered today that it seems as if names which contains Swedish letters `åäö` does not work. This is unfortunate, and I suspect this extends to other non-english letters as well?

I always use English when naming variables, but not in this case since these placeholders are to be used in a (Swedish) text context. So instead of using `{owner}` I really want to use `{ägare}` (= owner in Swedish). This is useful because it makes it easier to adhere to correct grammar etc. and improves the experience for non-technical colleagues.

**Comment by sindresorhus** [comment]
I prefer to keep it ASCII. Supporting Swedish would not be a big problem, but then users would expect any language to be supported, and that complicates it.
