### ISSUE TITLE
Encoding as HTML Entities to avoid code injection

### ISSUE THREAD

**Issue by sbrl** [sindresorhus/pupa#4]
If the output is for a browser, then it can be a security issue (code injection, etc.) if the values are simply dumped straight into the output - rather, they should be encoded as HTML entities. To that end, it's annoying doing it oneself before passing data to the templating engine. Is it planned to add support for this directly to pupa?

e.g. Maybe single braces `{}` means do it normally, and double braces (`{{}}`) could mean "escape it too please"? Or even the other way around.

**Comment by sindresorhus** [comment]
I never considered that type of usage, but sure. Double-braces would be a good syntax for that.

**Comment by mgenware** [comment]
IMHO, as this library can run on browser and node, to keep it lightweight, it should be user's responsibility to do necessary escaping, there are already plenty of dedicated libs for this and if you're using this to render HTML, you may also consider using a template engine

**Comment by sbrl** [comment]
Wait. So this isn't a templating engine @mgenware? What is the purpose of it then?

**Comment by sbrl** [comment]
Awesome, thanks :fireworks:
